### ISSUE TITLE
work on no root locale setting

### ISSUE THREAD

**Issue by toramameseven** [HiDeoo/starlight-i18n#3]
### Is your feature request related to a problem?

This works on [root locale](https://starlight.astro.build/guides/i18n/#use-a-root-locale) configuration. I want it to work on [no root locale setting](https://starlight.astro.build/guides/i18n/#configure-i18n). Only for my environment?

### Describe the solution you'd like

sorry no solutions.

**Comment by HiDeoo** [comment]
Thanks for your report 🙌 

The issue should be fixed in the next version with the changes from https://github.com/HiDeoo/starlight-i18n/pull/5. There are a few more changes I would like to get in before the next release but this should be fairly soon.
